codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
        branches: [main, develop]
    patch:
      default:
        target: auto
        threshold: 0%
  precision: 2

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "node_modules/*"
  - "coverage/*"
  - "go-wrapper/*"
  - "js-wrapper/*"


fixes:
  - "::src/"

flags:
  unittests:
    paths:
      - "test/*"

parsers:
  js:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
