name: CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run test and generate coverage
        run: npm run lcov

        ## This step will only be executed if the actions variable CODECOV_BRANCHES
        ## is set as an array of branches to upload to Codecov. 
        ## Example --var CODECOV_BRANCHES='["main", "feature-1"]'
      - name: Upload coverage to Codecov
        if: ${{ vars.CODECOV_BRANCHES && contains(fromJson(vars.CODECOV_BRANCHES), github.ref_name) }}
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          verbose: true
