name: CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run test and generate coverage
        run: npm run lcov

        ## This step will only be executed if the actions variable CODECOV_BRANCHES
        ## is set as an array of branches to upload to Codecov. 
        ## Example --var CODECOV_BRANCHES='["main", "feature-1"]'
      - name: Upload coverage to Codecov
        if: ${{ contains(fromJson(vars.CODECOV_BRANCHES), github.ref_name)  }}
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          verbose: true
