name: CI

permissions:
  contents: read

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run test and generate coverage
        run: npm run lcov

        ## This step will only be executed if the actions variable CODECOV_BRANCHES
        ## is set as an array of branches to upload to Codecov. 
        ## Example --var CODECOV_BRANCHES='["main", "feature-1"]'
      - name: Upload coverage to Codecov
        if: ${{ vars.CODECOV_BRANCHES && contains(fromJson(vars.CODECOV_BRANCHES), github.ref_name) }}
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          verbose: true
